exec-once = $terminal
exec-once = awww-daemon &
exec-once = swaync &
exec-once = hypridle &
exec-once = systemctl --user start hyprpolkitagent
exec-once = wl-paste --watch cliphist store &
exec-once = hyprpm reload -n
exec-once = qs &

exec = gsettings set org.gnome.desktop.interface gtk-theme "Adwita-dark" &
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark" &
exec = kbuildsycoca6 &


